name: Deploy to Server (Self-hosted Runner)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
 
    steps:
      - name: Execute Deploy Script
        run: |
          cd ~/flaskapp/address
          git fetch origin main
          git reset --hard origin/main
          cd ~/flaskapp            
          
          # 💡 [치트키 추가] 새 네트워크 옵션을 깨끗하게 반영하기 위해, 기존 네트워크와 찌꺼기 컨테이너를 확실하게 청소!
          docker-compose down --remove-orphans
          
          # 이제 완전히 깨끗해진 판 위에 'was-host3'를 무결하게 빌드 후 구동합니다.
          docker-compose up -d --build was-host3